- signals.mml
- signals.mss
Fixes #16.
Changes:
* render all signals at derailers and buffer stops
* do not require `railway:signal:direction` at derailers.
* German signal Sh 0 as sign is tagged `railway:signal:minor=DE-ESO:sh0`, not `railway:signal:minor=DE-ESO:sh`.
> Signals at buffer stops and derailers

- sql/get_station_importance.sql
Some stations are not rendered on medium zoom levels although they have a relatively high `route_count`. The route count is computed correctly but overwritten by the default value because the query set is not sorted when `SELECT DISTINCT ON` is applied. Sometimes the computed value was chosen, sometimes the default (0).
> Bugfix station importance: Make some stations not disappear randomly

- project.mml
> Render all tracks with railway:track_ref in railway_text_detail layer

- signals.mss
Mapnik regular expressions must match the whole string, not a part of it (like grep -Ex).
Fixes #26
> Fix regular expression in signals style

- project.mml
On zoom level 15 and above the route number and/or name was only rendered if both were tagged because the string concatenation using `||` returns NULL if any of the strings to be concatenated is null. This affects the railway_text_high and railway_text_detail layers.
Before:
After:
Location: https://www.openrailwaymap.org/?lang=null&lat=49.0009130690859&lon=8.42961698770523&zoom=18&style=standard
> Render at least ref=* or name=* if one of the two is NULL

- sql/osm_carto_views.sql
- standard.mml
By using z_order, we override our custom sorting of tracks with the sorting by the Lua script of OSM Carto which ranks abandoned tracks above normal tracks.
Before:
After:
> Fix order of track types: do not rely on z_order

- standard_labels.mss
Reimplementation of https://github.com/OpenRailwayMap/OpenRailwayMap/pull/629 in CartoCSS
> Render station=subway/light_rail in italic font

- SETUP.md
util/prepare_makefile.sh was an intermediate development step in https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/21 but removed before the merge and is not directly visible in the Git
history due to a squashing rebase before the merge into the master branch.
Reported by @hholzgra on IRC.
> Improve setup guide w.r.t. Makefile setup

- maxspeed.mml
- signals.mml
The standad style switched to layer instead of z_order for ordering in https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/32 That pull request changed the definitions of the database views by removing the z_order column. This regression broke the other styles.
> Switch maxspeed and signals style to layer instead of z_order

- sql/functions.sql
Per [documentation of key:electrified on OSM](https://wiki.openstreetmap.org/wiki/Key:electrified?uselang=en).
Should fix issue of the London Underground displaying as gray lines on the electrification style. (Milan Line M1 I read also uses fourth rail, but isn't tagged as such on OSM.)
> Add 4th_rail to electrification valid_values

- maxspeed_signals.mss
This PR adds Zs 3 ? and Zs 3v ? to the mss file. Icons were already in the symbols directory.
Maybe it could be nice to have a different rendering of unknown/empty light signals Zs 2(v) and Zs 3(v) through a triangular (Zs3(v)) or squared (Zs2(v)) box?
This PR resolves issue #51
>  add "Zs3 ?" and "Zs3v ?" icons #51 

- sql/get_station_importance.sql
It will fail if the materialized view exists already. This patch makes running Ansible easier.
> Make SQL script idempotent

- signals.mml
- sql/functions.sql
- train_protection.mss
This PR aims at completing the experience of Openrailwaymap.org, where French systems are already part of the visible legend.
A tag search indicates more than 30 thousand of way objects already tagged.
The colors of the rendering have been taken from the legend repository.
Fixes: #70 70
> ADD: rendering of French signalling systems KVB and TVM

- signals.mml
- sql/functions.sql
- train_protection.mss
Hi! This PR copies https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/77 but rebased on the latest master.
In addition I made two changes:
- slightly changed the PTC color, due to recent use of the same color for SCMT signalling (although the continent is different)
- renamed a function that had 'etcs' in the name but now is not just used with etcs data
> Added rendering for PTC + rebase & adjustments

- train_protection.mss
"construction_etcs=no" must be added as a condition for "line-color: @no_train_protection_color", otherwise that block always gets priority over "line-color: @etcs_construction_color" regardless of the order of the blocks.
> FIX: etcs=no prioritized over construction_etcs!=no (#91)

- signals.mml
- sql/functions.sql
- train_protection.mss
Adds rendering for ZSI 127, the narrow gauge train protection system that's being rolled out in Switzerland (sadly most information on it is only available in German, like at https://de.wikipedia.org/wiki/Zugsicherung_auf_Schmalspurbahnen_in_der_Schweiz#ZSI-127 ). I struggled quite a bit with choosing a color, so absolutely open to changing it.
The reason I chose to give it priority 3 is that there are technically "worse" narrow gauge train protection systems that are being used alongside ZSI 127 - though barely any of that is mapped. Further, on some three or four rail segments there might be ZSI 127 and ETCS available.
> Add rendering for ZSI 127

- sql/functions.sql
- train_protection.mss
This PR is motivated by a discussion here:
https://github.com/OpenRailwayMap/OpenRailwayMap/issues/827
The idea is to simplify part of the code, concentrating the (complex) logic about detecting the lack of train protection in the SQL functions instead of duplicating it in the color-selecting code.
TESTS:
Ljubjiana on ORM:
Ljubjiana on local Kosmtik after the changes:
> MOD: delegate 'no signalling' logic from CSS to SQL

- gauge.mss
This is only a minimal change to distinguish the metro lines in Barcelona with gauge ~1674 from other nearby tracks with gauge 1668.
> Track gauge for Barcelona Metro lines

- maxspeed_signals.mss
- symbols/de/bostrab/g2a-5.svg
I created the SVG by mixing the existing 15 km/h sign with the 0 from the ESO-lf7 signs.
Example rendering in Nuremberg around Christuskirche.
> Add BOStrab g2a 5 km/h signal image

- signals.mml
This happens because we query for the wrong tag.
Wrong:
`railway:signal:crossing:distant:shortened=yes`
Correct:
`railway:signal:crossing_distant:shortened=yes`
See also: https://overpass-turbo.eu/s/1DBg
Example rendering
> Fix shortened BÜ2 not rendering

- signals.mss
Example rendering north west of Treuchtlingen:
> Add rendering for ESO Bü3 sign

- signals.mml
- signals.mss
Very straightforward, example in Rauenstein (Thür):
> Ne13 and Ne12 rendering

- maxspeed_signals.mss
Fixes the signal not showing up.
Example in Nuremberg:
And in Hochspeyer:
(Also sorry for the PR spam, I'm testing many things one by one here)
> Fix Zs10 not rendering

- signals.mss
Fixes #50 
I simplified the code to make use of the implicit else CartoCSS has. Additionally, the Blockkennzeichen is now showing it's ref like a normal signal if not using the flex shied container. (I hope that's okay)
Example renderings at the location mentioned in the issue:
Zoom 15:
Zoom 16:
Zoom 17:
> Fix ESO Blockkennzeichen rendering issues

- signals.mml
- sql/functions.sql
- train_protection.mss
Added support for CTCS following discussion here:
https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/issues/37
TODO: finalize color, we can discuss here.
> Rendering of Chinese CTCS signalling

- signals.mss
I have added the rendering of BOStrab train control signals in this PR. These are similar to the DE-EBO Ks signal system, so I simply used the existing SVG. Is that ok?
(The two signals you can see are incorrectly tagged in OSM as "Ks signals")
> add BOStrab combined signals
